// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteTec.Infra.Data.Context;

namespace TesteTec.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteTec.Domain.Entities.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeDimensao")
                        .IsRequired()
                        .HasColumnName("NomeDimensao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Dimensao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeDimensao = "C001"
                        },
                        new
                        {
                            Id = 2,
                            NomeDimensao = "C002"
                        },
                        new
                        {
                            Id = 3,
                            NomeDimensao = "C003"
                        },
                        new
                        {
                            Id = 4,
                            NomeDimensao = "C137"
                        });
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Morty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Morty");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Rick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDimensao")
                        .HasColumnName("IdDimensao")
                        .HasColumnType("int");

                    b.Property<int>("IdMorty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDimensao");

                    b.HasIndex("IdMorty");

                    b.ToTable("Ricks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdDimensao = 1,
                            IdMorty = 1
                        },
                        new
                        {
                            Id = 2,
                            IdDimensao = 2,
                            IdMorty = 2
                        },
                        new
                        {
                            Id = 3,
                            IdDimensao = 3,
                            IdMorty = 3
                        },
                        new
                        {
                            Id = 4,
                            IdDimensao = 4,
                            IdMorty = 4
                        });
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDimensao")
                        .HasColumnName("IdDimensao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDimensao");

                    b.ToTable("Viagem");
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Rick", b =>
                {
                    b.HasOne("TesteTec.Domain.Entities.Dimensao", "Dimensao")
                        .WithMany()
                        .HasForeignKey("IdDimensao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteTec.Domain.Entities.Morty", "Morty")
                        .WithMany()
                        .HasForeignKey("IdMorty")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesteTec.Domain.Entities.Viagem", b =>
                {
                    b.HasOne("TesteTec.Domain.Entities.Dimensao", "Dimensao")
                        .WithMany()
                        .HasForeignKey("IdDimensao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
